[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway-frontend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = ""

[env]
PORT = "80"