version: '3.8'

services:
  # Backend Service with built frontend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: printer-automater-backend-prod
    ports:
      - "3003:3003"
    environment:
      - HOST=0.0.0.0
      - PORT=3003
      - DEBUG=false
      - DOCKER_ENV=true
      - FRONTEND_URL=http://localhost:3003
    env_file:
      - .env
    volumes:
      # Mount the .env file for persistent configuration
      - ./.env:/app/.env:ro
      # Mount local images directory if needed
      - ./server/images:/app/server/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge 