[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway-backend"

[deploy]
startCommand = "python server/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]