# Railway Multi-Service Configuration for Etsy Seller Automater
# This configuration supports the microservices architecture with:
# - Web API service
# - Background worker services  
# - Print job processing workers
# - Task scheduler service
# - PostgreSQL database
# - Redis for queues/caching

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway-backend"

[deploy]
startCommand = "python server/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

# Environment variables for all services
[env]
HOST = "0.0.0.0"
PORT = "3003"
DEBUG = "false"
DOCKER_ENV = "railway"
# Database and Redis URLs are automatically provided by Railway plugins
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
REDIS_URL = "${{ Redis.REDIS_URL }}"
# Application secrets
JWT_SECRET = "${{ JWT_SECRET }}"
ETSY_API_KEY = "${{ ETSY_API_KEY }}"
ETSY_CLIENT_SECRET = "${{ ETSY_CLIENT_SECRET }}"
# QNAP NAS configuration for file storage
QNAP_HOST = "${{ QNAP_NAS_HOST }}"
QNAP_USERNAME = "${{ QNAP_NAS_USERNAME }}"
QNAP_PASSWORD = "${{ QNAP_NAS_PASSWORD }}"
QNAP_PORT = "22"
NAS_BASE_PATH = "/share/Graphics"
# Frontend URL for CORS
FRONTEND_URL = "${{ FRONTEND_URL }}"