version: '3.8'

services:
  token-refresh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: token-refresh-service
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ETSY_CLIENT_ID=${ETSY_CLIENT_ID}
      - ETSY_CLIENT_SECRET=${ETSY_CLIENT_SECRET}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - REFRESH_INTERVAL_MINUTES=${REFRESH_INTERVAL_MINUTES:-3}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/var/log
    # Connect to existing database - no need for separate DB
    # Make sure DATABASE_URL points to your main application database
