[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Main API Service
[[services]]
name = "api"
source = "."

[services.api.variables]
ENABLE_CACHING = "true"
CACHE_TTL_SECONDS = "300"
CACHE_MAX_MEMORY_ITEMS = "1000"
DEBUG_LOGGING = "false"
PERFORMANCE_MONITORING = "true"

[services.api.deploy]
numReplicas = 1
sleepApplication = false

# Redis Service in separate directory
[[services]]
name = "redis"
source = "./redis"

[services.redis.variables]
REDIS_PORT = "6379"
REDIS_MAXMEMORY = "1gb"
REDIS_MAXMEMORY_POLICY = "allkeys-lru"

[services.redis.deploy]
numReplicas = 1